language: generic
addons:
  ssh_known_hosts: mint.isi.edu
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.23.2
  global:
  - secure: i9aY0zZGDJb6X4Y8F1NBKeoZbRIouFDNlnAUS9mRFSoO0T1zPabElIC6cx0AZ9EM4Ka8An+VoOqWmdthK/1ulYMKJhkGv4RcwpfKLIDscNMUpQsoypfYqeU9QcJ6trscI/ivLUrfT64d+XdjMKZ7KJeuIIBNgia+WT5cynPb03I9K9N69lDTrBVL3zQ5fgMezcf6NKUR4nTULgrRckIHDv/X0UoMsmhgij5kg3dnChEpacZDYKdFkW22L4WIrdebPZS2fD3wY6IOUWE5SwSo/y62FcOqSs6uYlX+g82RhRPSVAJpnlms/9crroC2C7RHdjKbEmpmcI7vLPmWbXL/ftGx7bl1wHSuuR8iV7bxueRr+Ygo2Njz1L5ZJZfdCD4Ul5o5lmQ3buqW+vhNWdmLcwlWTBw/Y7rqqc5e5JIMXluVcPbGKGOA0dNu4RGzHodODlc+kct096Lvu4SkUoeyOwflsAD/2qha5RM3gnVxKp/+aE3pEKNaIn+MBZtcFMJEQGLOYxAM+kWoENrPoLc/BYJ4RStOUYr7znvgl6KwyWGu6cLU5NaZebRJsu0AsnDMudMKfz2cS7jHXGxxe6pihIk9OMATCGkemvleLr4m9cXdSwjNh8bNrSmWIf9SGljfjeRP+yk8TbwVmhnP2iqCbF8gwGGaww3cEk5UKsqZ8D0=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_af150e6bb5bf_key -iv $encrypted_af150e6bb5bf_iv
  -in google-api-key.ts.enc -out src/config/google-api-key.ts -d
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose build
- docker-compose up -d prod
- docker cp $(docker-compose ps -q prod):/usr/share/nginx/html/ $TRAVIS_BUILD_DIR/mint-standalone-model-catalog/
before_deploy:
- echo $key_pass | gpg --passphrase-fd 0 id_travis_rsa.gpg
- eval "$(ssh-agent -s)"
- chmod 600 id_travis_rsa
- ssh-add id_travis_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh $TRAVIS_BUILD_DIR/mint-standalone-model-catalog model-catalog_$TRAVIS_BRANCH
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master)$"
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh $TRAVIS_BUILD_DIR/mint-standalone-model-catalog model-catalog_$TRAVIS_TAG
  on:
    tags: true
    all_branches: true
