#Environment dev
version: '3'
services:
  prod:
    build: 
      context: .
    image: "mint-project/modelexplorer:latest"
    volumes:
      - ./build:/home/node/app
    ports:
      - 12123:80        
